### PR TITLE
Fix passing of CODECOV_TOKEN to Travis

### PR DESCRIPTION
**Pull request by domq**
This problem is currently causing Travis to fail, see e.g. https://travis-ci.org/epfl-idevelop/jahia2wp/builds/284991266?utm_source=github_status&utm_medium=notification

### CODE REVIEW

**Comment by domq** [comment]
Arright, this was not it: https://travis-ci.org/epfl-idevelop/jahia2wp/builds/285017596?utm_source=github_status&utm_medium=notification 

Please bear with me as I shotgun-debug my way out of this, pushing a rebased version of this PR every time until I can get Travis to give us a green...

**Comment by domq** [comment]
Now [build #292](https://travis-ci.org/epfl-idevelop/jahia2wp/builds/285021903?utm_source=github_status&utm_medium=notification) is green, but codecov is not running. Still looking... [Testing with Docker](https://github.com/codecov/support/wiki/Testing-with-Docker#codecov-inside-docker) may or may not be of interest.

**Comment by ebreton** [comment]
Hi @domq , 

I think I fixed this in branch feature-bonus :)
PR #33

**Comment by domq** [comment]
Sweet! [I got it right](https://travis-ci.org/epfl-idevelop/jahia2wp/builds/285030415?utm_source=github_status&utm_medium=notification). Let me cherry-pick this into a brand new PR and close this one.

**Pull request closed without merging**
