### PR TITLE
porting crawler from jahiap

### PR DESCRIPTION
**Pull request by ebreton**
## Changes

**high level:**
1. added command `download`
1. added vars `JAHIA_*` in  `.env.sample`, please update your `.env` file to make use of the download command

**low level:**
1. migrate crawler from jahiap
1. break code into modules `SessionHandler`, `JahiaConfig`, `JahiaCrawler`
1. support username, password, host from either .env or CLI arguments
1. added tests

## Conclusion

The purpose of this PR was to get a feeling: **what rocks are on the path of moving our code from prototyping to production?**

1. More than half of the effort lies in the **creation of automatic tests**. 
> In this case, having successfull tests with a satisfying coverage (from 0% to >90%) took 2/3 of the effort (and depended on the next point...)
2. The **change of environment** has to be taken into account: using standard WP in a new management container creates some surprises...
> In this precise case, the surprise came from travis, where the repository directory in the container is read-only. Changes had to be done in order to be able to test the successfull download of a Jahia zip in `/tmp`
3. The second biggest part of the work is the **command line interface (CLI)**. Presenting appropriate commands and options through the CLI. The prototype was built 1) first to manage two sites, 2) secondly to scale to 650 sites. Those two approaches clearly structured the CLI of the prototype, from hardcoding a couple of case to support batch treatment. The new code is neither of both case: it needs to handle a source of trust (kind of batch treatment) but also single usages by external users (actions need to be configurable, and customizable via CLI)
> In this case, the users need to be able to set / define their JAHIA credentials, whereas the old system "hardcoded" them from environment variables
4. **Architecture** of the code needs refactoring, separation of responsibilities.
> In this case, one file was split into three: session handling, configuration and crawling

### CODE REVIEW

**Comment by ebreton** [comment]
Les tests ne passent pas sur Travis car il n'accepte pas d'écrire un fichier sur le FS

```
 # download file
        logging.info("saving response into %s...", self.config.file_path)
>       with open(self.config.file_path, 'wb') as output:
E       PermissionError: [Errno 13] Permission denied: '/srv/test/jahia2wp/src/crawler/tests/non-existing-site_export_2017-10-11-05-03.zip'
src/crawler/crawler.py:64: PermissionError
```

je regarde...

**Comment by ebreton** [comment]
> Les tests ne passent pas sur Travis car il n'accepte pas d'écrire un fichier sur le FS

résolu en passant le chemin d'export des zip_path en option CLI. Ce qui permet de faire travailler travis dans `/tmp`

**Comment by ebreton** [comment]
Du coup @GregLeBarbar , tu as pu regarder un peu la PR ? merge ? :)

**Comment by GregLeBarbar** [comment]
@ManuBreton : Yep ! Merge !

2017-10-19 22:23 GMT+02:00 Manu <notifications@github.com>:

**Pull request merged**
